# Generated by Django 5.2.1 on 2025-11-07 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_and_entitys', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='xx_UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level_order', models.PositiveIntegerField(default=1, help_text='Order of the level for hierarchy')),
            ],
            options={
                'db_table': 'XX_USER_LEVEL_XX',
                'ordering': ['level_order'],
            },
        ),
        migrations.CreateModel(
            name='xx_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('superadmin', 'SuperAdmin')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('can_transfer_budget', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('user_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='user_management.xx_userlevel')),
            ],
            options={
                'db_table': 'XX_USER_XX',
            },
        ),
        migrations.CreateModel(
            name='xx_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_system_read', models.BooleanField(default=False)),
                ('is_shown', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'XX_NOTIFICATION_XX',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_legacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'XX_USER_PROJECTS_XX',
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='xx_UserAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, choices=[('edit', 'edit'), ('approve', 'approve')], max_length=50, null=True)),
                ('Entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_abilities_legacy', to='account_and_entitys.xx_entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities_legacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'XX_USER_ABILITY_XX',
                'unique_together': {('user', 'Entity', 'Type')},
            },
        ),
        migrations.CreateModel(
            name='XX_UserSegmentAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_type', models.CharField(choices=[('EDIT', 'Edit/Modify'), ('APPROVE', 'Approve'), ('VIEW', 'View'), ('DELETE', 'Delete'), ('TRANSFER', 'Transfer Budget'), ('REPORT', 'Generate Reports')], help_text='Type of ability granted', max_length=20)),
                ('segment_combination', models.JSONField(help_text="Segment combination as {segment_type_id: segment_code}. Example: {1: 'E001', 2: 'A100'}")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this ability is currently active')),
                ('granted_at', models.DateTimeField(auto_now_add=True, help_text='When ability was granted')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this ability')),
                ('granted_by', models.ForeignKey(blank=True, help_text='User who granted this ability', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_abilities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who has this ability', on_delete=django.db.models.deletion.CASCADE, related_name='segment_abilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'XX_USER_SEGMENT_ABILITY_XX',
                'ordering': ['user', 'ability_type'],
                'indexes': [models.Index(fields=['user', 'ability_type', 'is_active'], name='XX_USER_SEG_user_id_fda11d_idx'), models.Index(fields=['ability_type', 'is_active'], name='XX_USER_SEG_ability_613169_idx')],
            },
        ),
        migrations.CreateModel(
            name='XX_UserSegmentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('VIEW', 'View Only'), ('EDIT', 'Edit'), ('APPROVE', 'Approve'), ('ADMIN', 'Administrator')], default='VIEW', help_text='Level of access granted', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this access is currently active')),
                ('granted_at', models.DateTimeField(auto_now_add=True, help_text='When access was granted')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this access')),
                ('granted_by', models.ForeignKey(blank=True, help_text='User who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(help_text='Specific segment value', on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='account_and_entitys.xx_segment')),
                ('segment_type', models.ForeignKey(help_text='Type of segment (Entity, Account, Project, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='account_and_entitys.xx_segmenttype')),
                ('user', models.ForeignKey(help_text='User who has access to this segment', on_delete=django.db.models.deletion.CASCADE, related_name='segment_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'XX_USER_SEGMENT_ACCESS_XX',
                'ordering': ['segment_type', 'segment', 'access_level'],
                'indexes': [models.Index(fields=['user', 'segment_type', 'is_active'], name='XX_USER_SEG_user_id_8b7720_idx'), models.Index(fields=['segment', 'is_active'], name='XX_USER_SEG_segment_a8d67c_idx')],
                'unique_together': {('user', 'segment_type', 'segment', 'access_level')},
            },
        ),
    ]
