# Generated by Django 4.2.7 on 2025-12-10 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0009_alter_xx_gfs_mamping_same'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XX_SecurityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text="Unique name for this security group (e.g., 'Finance Department', 'IT Team')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description of this security group's purpose and responsibilities")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this group is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this group was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_security_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'XX_SECURITY_GROUP_XX',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='XX_SecurityGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is currently active in the group')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='When this role was added to the group')),
                ('added_by', models.ForeignKey(blank=True, help_text='User who added this role to the group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_group_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role/user level available in this group', on_delete=django.db.models.deletion.CASCADE, related_name='security_group_assignments', to='user_management.xx_userlevel')),
                ('security_group', models.ForeignKey(help_text='Security group this role belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='group_roles', to='user_management.xx_securitygroup')),
            ],
            options={
                'db_table': 'XX_SECURITY_GROUP_ROLE_XX',
                'ordering': ['security_group', 'role'],
            },
        ),
        migrations.CreateModel(
            name='XX_SecurityGroupSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this segment is currently active in the group')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='When this segment was added to the group')),
                ('added_by', models.ForeignKey(blank=True, help_text='User who added this segment to the group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_group_segments', to=settings.AUTH_USER_MODEL)),
                ('security_group', models.ForeignKey(help_text='Security group this segment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='group_segments', to='user_management.xx_securitygroup')),
                ('segment', models.ForeignKey(help_text='Specific segment value accessible by this group', on_delete=django.db.models.deletion.CASCADE, related_name='security_group_assignments', to='account_and_entitys.xx_segment')),
                ('segment_type', models.ForeignKey(help_text='Type of segment (must be a required segment)', on_delete=django.db.models.deletion.CASCADE, related_name='security_group_assignments', to='account_and_entitys.xx_segmenttype')),
            ],
            options={
                'db_table': 'XX_SECURITY_GROUP_SEGMENT_XX',
                'ordering': ['security_group', 'segment_type', 'segment'],
            },
        ),
        migrations.CreateModel(
            name='XX_UserGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently active')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the user joined this group')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this membership')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned this user to the group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_group_memberships', to=settings.AUTH_USER_MODEL)),
                ('assigned_roles', models.ManyToManyField(help_text='Roles assigned to this user within the group (1-2 roles)', related_name='user_assignments', to='user_management.xx_securitygrouprole')),
                ('assigned_segments', models.ManyToManyField(blank=True, help_text='Specific segments this member can access. If empty, member sees all group segments.', related_name='member_assignments', to='user_management.xx_securitygroupsegment')),
                ('security_group', models.ForeignKey(help_text='Security group the user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='user_management.xx_securitygroup')),
                ('user', models.ForeignKey(help_text='User who is a member of this group', on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'XX_USER_GROUP_MEMBERSHIP_XX',
                'ordering': ['security_group', 'user'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='XX_USER_GRO_user_id_4cda93_idx'), models.Index(fields=['security_group', 'is_active'], name='XX_USER_GRO_securit_bac9ec_idx')],
                'unique_together': {('user', 'security_group')},
            },
        ),
        migrations.AddIndex(
            model_name='xx_securitygroupsegment',
            index=models.Index(fields=['security_group', 'is_active'], name='XX_SECURITY_securit_49b765_idx'),
        ),
        migrations.AddIndex(
            model_name='xx_securitygroupsegment',
            index=models.Index(fields=['segment_type', 'is_active'], name='XX_SECURITY_segment_228b71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xx_securitygroupsegment',
            unique_together={('security_group', 'segment_type', 'segment')},
        ),
        migrations.AddIndex(
            model_name='xx_securitygrouprole',
            index=models.Index(fields=['security_group', 'is_active'], name='XX_SECURITY_securit_0856b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xx_securitygrouprole',
            unique_together={('security_group', 'role')},
        ),
        migrations.AddIndex(
            model_name='xx_securitygroup',
            index=models.Index(fields=['group_name', 'is_active'], name='XX_SECURITY_group_n_af7986_idx'),
        ),
    ]
