# Generated by Django 4.2.7 on 2025-12-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_xx_securitygroup_xx_securitygrouprole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_securitygrouprole',
            name='default_abilities',
            field=models.JSONField(blank=True, default=list, help_text="Default abilities for all users with this role. Example: ['TRANSFER', 'APPROVE']"),
        ),
        migrations.AddField(
            model_name='xx_usergroupmembership',
            name='custom_abilities',
            field=models.JSONField(blank=True, default=list, help_text="User-specific abilities override. If empty, uses role's default_abilities. Example: ['TRANSFER', 'APPROVE', 'VIEW']"),
        ),
    ]
