# Generated by Django 4.2.7 on 2025-12-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_xx_securitygrouprole_default_abilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_notification',
            name='Transaction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xx_notification',
            name='Type_of_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xx_notification',
            name='type_of_notification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
