# Generated by Django 4.2.7 on 2025-12-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_xx_notification_transaction_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xx_notification',
            old_name='type_of_notification',
            new_name='type_of_Trasnction',
        ),
    ]
