# Generated by Django 4.2.7 on 2025-12-31 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_rename_type_of_notification_xx_notification_type_of_trasnction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xx_notification',
            old_name='message',
            new_name='ara_message',
        ),
        migrations.AddField(
            model_name='xx_notification',
            name='eng_message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
