# Generated by Django 4.2.7 on 2026-01-02 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_management', '0006_rename_message_xx_notification_ara_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XX_AuditLoginHistory',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('login_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('FAILED_LOGIN', 'Failed Login'), ('TOKEN_REFRESH', 'Token Refresh')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('success', models.BooleanField(default=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'db_table': 'XX_AUDIT_LOGIN_HISTORY_XX',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='XX_AUDIT_LO_user_id_121e72_idx'), models.Index(fields=['username', '-timestamp'], name='XX_AUDIT_LO_usernam_1a6ae1_idx')],
            },
        ),
        migrations.CreateModel(
            name='XX_AuditLog',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, help_text='Username at time of action (preserved even if user deleted)', max_length=255, null=True)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('SUBMIT', 'Submit'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('PERMISSION_CHANGE', 'Permission Change'), ('WORKFLOW', 'Workflow Action'), ('OTHER', 'Other')], help_text='Type of action performed', max_length=50)),
                ('action_description', models.TextField(help_text='Human-readable description of the action')),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', help_text='Severity level of the action', max_length=20)),
                ('endpoint', models.CharField(blank=True, help_text='API endpoint or view name', max_length=500, null=True)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, PUT, DELETE, etc.)', max_length=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request', null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the affected object', null=True)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the affected object', max_length=500, null=True)),
                ('old_values', models.TextField(blank=True, help_text='JSON representation of values before change', null=True)),
                ('new_values', models.TextField(blank=True, help_text='JSON representation of values after change', null=True)),
                ('metadata', models.TextField(blank=True, help_text='Additional metadata as JSON', null=True)),
                ('status', models.CharField(default='SUCCESS', help_text='Status of the action (SUCCESS, FAILED, PARTIAL)', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action was performed')),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration of the action in milliseconds', null=True)),
                ('module', models.CharField(blank=True, db_index=True, help_text='Django app/module name', max_length=100, null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of model affected by the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'XX_AUDIT_LOG_XX',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='XX_AUDIT_LO_user_id_b2f797_idx'), models.Index(fields=['action_type', '-timestamp'], name='XX_AUDIT_LO_action__55ee3b_idx'), models.Index(fields=['module', '-timestamp'], name='XX_AUDIT_LO_module_e7db80_idx'), models.Index(fields=['content_type', 'object_id'], name='XX_AUDIT_LO_content_61d875_idx')],
            },
        ),
    ]
