# Generated by Django 5.2.1 on 2025-11-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000)),
                ('original_message', models.TextField(blank=True, max_length=5000, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('edit_history', models.JSONField(blank=True, default=list, help_text='List of previous versions with timestamps')),
                ('seen', models.BooleanField(default=False, help_text='Whether the message has been seen by the recipient')),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='budget_management.xx_budgettransfer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
