# Generated by Django 5.2.1 on 2025-11-07 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chatting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['timestamp'], name='Chatting_ch_timesta_23c930_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user_from', 'user_to'], name='Chatting_ch_user_fr_7a552f_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['transaction'], name='Chatting_ch_transac_afde85_idx'),
        ),
    ]
