# Generated by Django 5.2.5 on 2025-12-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_xx_transactiontransfer_total_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=500, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='approved_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=500, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='available_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=500, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='budget_adjustments',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=500, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='commitments',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=500, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='encumbrance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=500, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='expenditures',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=500, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='from_center',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=500, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='initial_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=500, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='obligations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=500, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='other_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=500, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='to_center',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=500, null=True),
        ),
        migrations.AlterField(
            model_name='xx_transactiontransfer',
            name='total_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=500, null=True),
        ),
    ]
