# Generated by Django 4.2.7 on 2025-11-26 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('function_name', models.CharField(help_text="Name of the Python function that retrieves this datasource's value", max_length=255)),
                ('parameter_names', models.JSONField(default=list, help_text='List of parameter names required by the function')),
                ('return_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('string', 'String'), ('boolean', 'Boolean')], default='float', help_text='Expected return type of the function', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed_success', 'Completed - Success'), ('completed_failure', 'Completed - Failure'), ('paused', 'Paused'), ('error', 'Error')], default='running', max_length=30)),
                ('context_data', models.JSONField(default=dict, help_text='Execution context - can store input data, results, etc.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_expression', models.TextField(help_text='Left side of comparison. Can be a number, datasource:name, or arithmetic expression')),
                ('operation', models.CharField(choices=[('==', 'Equals'), ('!=', 'Not Equals'), ('>', 'Greater Than'), ('<', 'Less Than'), ('>=', 'Greater Than or Equal'), ('<=', 'Less Than or Equal')], max_length=10)),
                ('right_expression', models.TextField(help_text='Right side of comparison. Can be a number, datasource:name, or arithmetic expression')),
                ('if_true_action', models.CharField(choices=[('proceed_to_step', 'Proceed to Next Step'), ('proceed_to_step_by_id', 'Proceed to Specific Step'), ('complete_success', 'Complete Workflow (Success)'), ('complete_failure', 'Complete Workflow (Failure)'), ('send_notification', 'Send Notification'), ('create_task', 'Create Task')], max_length=50)),
                ('if_true_action_data', models.JSONField(blank=True, default=dict, help_text='Additional data for the true action (e.g., next step ID, notification message)')),
                ('if_false_action', models.CharField(choices=[('proceed_to_step', 'Proceed to Next Step'), ('proceed_to_step_by_id', 'Proceed to Specific Step'), ('complete_success', 'Complete Workflow (Success)'), ('complete_failure', 'Complete Workflow (Failure)'), ('send_notification', 'Send Notification'), ('create_task', 'Create Task')], max_length=50)),
                ('if_false_action_data', models.JSONField(blank=True, default=dict, help_text='Additional data for the false action')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('initial_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_as_initial', to='django_dynamic_validation.validationstep')),
                ('steps', models.ManyToManyField(related_name='workflows', to='django_dynamic_validation.validationstep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationStepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_value', models.CharField(blank=True, max_length=500, null=True)),
                ('right_value', models.CharField(blank=True, max_length=500, null=True)),
                ('condition_result', models.BooleanField(blank=True, null=True)),
                ('executed_action', models.CharField(max_length=50)),
                ('action_result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='django_dynamic_validation.validationexecution')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dynamic_validation.validationstep')),
            ],
            options={
                'ordering': ['executed_at'],
            },
        ),
        migrations.AddField(
            model_name='validationexecution',
            name='current_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions_at_step', to='django_dynamic_validation.validationstep'),
        ),
        migrations.AddField(
            model_name='validationexecution',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='validationexecution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='django_dynamic_validation.validationworkflow'),
        ),
        migrations.CreateModel(
            name='DataSourceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters_used', models.JSONField(default=dict, help_text='Parameters passed to the function')),
                ('returned_value', models.CharField(help_text='Value returned by the function', max_length=500)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('execution_context', models.TextField(blank=True, help_text='Context in which the function was called (e.g., workflow execution ID)', null=True)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='django_dynamic_validation.datasource')),
            ],
            options={
                'verbose_name_plural': 'DataSource History',
                'ordering': ['-called_at'],
            },
        ),
        migrations.AddIndex(
            model_name='validationworkflow',
            index=models.Index(fields=['status', 'is_default'], name='django_dyna_status_20114c_idx'),
        ),
        migrations.AddIndex(
            model_name='validationstepexecution',
            index=models.Index(fields=['execution', 'step'], name='django_dyna_executi_6161f8_idx'),
        ),
        migrations.AddIndex(
            model_name='validationstep',
            index=models.Index(fields=['is_active', 'order'], name='django_dyna_is_acti_73929b_idx'),
        ),
        migrations.AddIndex(
            model_name='validationexecution',
            index=models.Index(fields=['workflow', 'status'], name='django_dyna_workflo_647df0_idx'),
        ),
        migrations.AddIndex(
            model_name='validationexecution',
            index=models.Index(fields=['started_at'], name='django_dyna_started_77fd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['name'], name='django_dyna_name_787aab_idx'),
        ),
    ]
