# Generated by Django 4.2.7 on 2025-11-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationstep',
            name='operation',
            field=models.CharField(choices=[('==', 'Equals'), ('!=', 'Not Equals'), ('>', 'Greater Than'), ('<', 'Less Than'), ('>=', 'Greater Than or Equal'), ('<=', 'Less Than or Equal'), ('in', 'In List'), ('not_in', 'Not In List')], max_length=10),
        ),
    ]
