# Generated by Django 4.2.7 on 2025-11-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_validation', '0002_add_in_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationstep',
            name='if_false_action',
            field=models.CharField(choices=[('proceed_to_step', 'Proceed to Next Step'), ('proceed_to_step_by_id', 'Proceed to Specific Step'), ('complete_success', 'Complete Workflow (Success)'), ('complete_failure', 'Complete Workflow (Failure)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='validationstep',
            name='if_true_action',
            field=models.CharField(choices=[('proceed_to_step', 'Proceed to Next Step'), ('proceed_to_step_by_id', 'Proceed to Specific Step'), ('complete_success', 'Complete Workflow (Success)'), ('complete_failure', 'Complete Workflow (Failure)')], max_length=50),
        ),
    ]
