# Generated by Django 4.2.7 on 2025-11-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_validation', '0003_remove_stub_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationstep',
            name='operation',
            field=models.CharField(choices=[('==', 'Equals'), ('!=', 'Not Equals'), ('>', 'Greater Than'), ('<', 'Less Than'), ('>=', 'Greater Than or Equal'), ('<=', 'Less Than or Equal'), ('in', 'In List'), ('not_in', 'Not In List'), ('contains', 'Contains'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('between', 'Between'), ('is_null', 'Is Null'), ('is_not_null', 'Is Not Null')], max_length=20),
        ),
    ]
