# Generated by Django 4.2.7 on 2025-11-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_validation', '0004_add_new_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationworkflow',
            name='execution_point',
            field=models.CharField(db_index=True, default='general', help_text="Where this workflow executes (e.g., 'on_transfer_submit', 'on_user_create')", max_length=100),
        ),
        migrations.AlterField(
            model_name='validationworkflow',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='validationworkflow',
            unique_together={('name', 'execution_point')},
        ),
        migrations.AddIndex(
            model_name='validationworkflow',
            index=models.Index(fields=['execution_point', 'status'], name='django_dyna_executi_2ba0a1_idx'),
        ),
    ]
