# Generated by Django 6.0 on 2025-12-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_validation', '0006_alter_datasource_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationstep',
            name='failure_message',
            field=models.TextField(blank=True, help_text='Custom user-friendly error message to display when this validation step fails', null=True),
        ),
    ]
