# Generated by Django 6.0 on 2025-12-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_validation', '0007_validationstep_failure_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationstep',
            name='x',
            field=models.FloatField(default=0, help_text='X coordinate for frontend positioning'),
        ),
        migrations.AddField(
            model_name='validationstep',
            name='y',
            field=models.FloatField(default=0, help_text='Y coordinate for frontend positioning'),
        ),
    ]
