# Generated by Django 6.0 on 2025-12-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_validation', '0008_validationstep_x_validationstep_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationstep',
            name='x',
            field=models.FloatField(help_text='X coordinate for frontend positioning'),
        ),
        migrations.AlterField(
            model_name='validationstep',
            name='y',
            field=models.FloatField(help_text='Y coordinate for frontend positioning'),
        ),
    ]
