# Generated by Django 6.0 on 2025-12-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_validation', '0009_alter_validationstep_x_alter_validationstep_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationstep',
            name='x',
            field=models.FloatField(blank=True, help_text='X coordinate for frontend positioning', null=True),
        ),
        migrations.AlterField(
            model_name='validationstep',
            name='y',
            field=models.FloatField(blank=True, help_text='Y coordinate for frontend positioning', null=True),
        ),
    ]
