# Generated by Django 5.2.5 on 2025-12-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dynamic_validation', '0010_alter_validationstep_x_alter_validationstep_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationstep',
            name='operation',
            field=models.CharField(choices=[('==', 'Equals'), ('!=', 'Not Equals'), ('>', 'Greater Than'), ('<', 'Less Than'), ('>=', 'Greater Than or Equal'), ('<=', 'Less Than or Equal'), ('in', 'In List (Exact)'), ('not_in', 'Not In List (Exact)'), ('in_contain', 'In List (Contains)'), ('not_in_contain', 'Not In List (Contains)'), ('in_starts_with', 'In List (Starts With)'), ('not_in_starts_with', 'Not In List (Starts With)'), ('contains', 'Contains'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('between', 'Between'), ('is_null', 'Is Null'), ('is_not_null', 'Is Not Null')], max_length=20),
        ),
    ]
