# Generated by Django 5.2.1 on 2025-11-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xx_BudgetTransfer',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(max_length=10)),
                ('requested_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('gl_posting_status', models.CharField(blank=True, max_length=50, null=True)),
                ('approvel_1', models.CharField(blank=True, max_length=100, null=True)),
                ('approvel_2', models.CharField(blank=True, max_length=100, null=True)),
                ('approvel_3', models.CharField(blank=True, max_length=100, null=True)),
                ('approvel_4', models.CharField(blank=True, max_length=100, null=True)),
                ('approvel_1_date', models.DateTimeField(blank=True, null=True)),
                ('approvel_2_date', models.DateTimeField(blank=True, null=True)),
                ('approvel_3_date', models.DateTimeField(blank=True, null=True)),
                ('approvel_4_date', models.DateTimeField(blank=True, null=True)),
                ('status_level', models.IntegerField(default=1)),
                ('attachment', models.CharField(blank=True, default='No', max_length=10, null=True)),
                ('fy', models.IntegerField(blank=True, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('interface_id', models.IntegerField(blank=True, null=True)),
                ('reject_group_id', models.IntegerField(blank=True, null=True)),
                ('reject_interface_id', models.IntegerField(blank=True, null=True)),
                ('approve_group_id', models.IntegerField(blank=True, null=True)),
                ('approve_interface_id', models.IntegerField(blank=True, null=True)),
                ('report', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'XX_BUDGET_TRANSFER_XX',
            },
        ),
        migrations.CreateModel(
            name='xx_DashboardBudgetTransfer',
            fields=[
                ('Dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'XX_DASHBOARD_BUDGET_TRANSFER_XX',
            },
        ),
        migrations.CreateModel(
            name='xx_BudgetTransferAttachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('file_data', models.BinaryField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('budget_transfer', models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='budget_management.xx_budgettransfer')),
            ],
            options={
                'db_table': 'XX_BUDGET_TRANSFER_ATTACHMENT_XX',
            },
        ),
        migrations.CreateModel(
            name='xx_BudgetTransferRejectReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_text', models.TextField(blank=True, null=True)),
                ('reject_date', models.DateTimeField(auto_now_add=True)),
                ('reject_by', models.CharField(blank=True, max_length=100)),
                ('Transcation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reject_reasons', to='budget_management.xx_budgettransfer')),
            ],
            options={
                'db_table': 'XX_BUDGET_TRANSFER_REJECT_REASON_XX',
            },
        ),
    ]
