# Generated by Django 5.2.5 on 2025-11-17 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='xx_budget_integration_audit',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=100)),
                ('step_number', models.IntegerField()),
                ('request_id', models.CharField(blank=True, max_length=50, null=True)),
                ('document_id', models.CharField(blank=True, max_length=50, null=True)),
                ('group_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_audits', to='budget_management.xx_budgettransfer')),
            ],
            options={
                'db_table': 'XX_BUDGET_INTEGRATION_AUDIT_XX',
                'ordering': ['transaction_id', 'step_number'],
            },
        ),
    ]
