# Generated by Django 5.2.5 on 2025-11-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management', '0002_xx_budget_integration_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_budget_integration_audit',
            name='Action_Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
