# Generated by Django 5.2.5 on 2025-11-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management', '0003_xx_budget_integration_audit_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_budgettransfer',
            name='control_budget',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
