# Generated by Django 5.2.5 on 2025-11-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management', '0004_xx_budgettransfer_control_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_budgettransfer',
            name='transfer_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
