# Generated by Django 4.2.7 on 2025-12-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management', '0005_xx_budgettransfer_transfer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xx_budgettransfer',
            name='approvel_1',
        ),
        migrations.RemoveField(
            model_name='xx_budgettransfer',
            name='approvel_1_date',
        ),
        migrations.RemoveField(
            model_name='xx_budgettransfer',
            name='approvel_2',
        ),
        migrations.RemoveField(
            model_name='xx_budgettransfer',
            name='approvel_2_date',
        ),
        migrations.RemoveField(
            model_name='xx_budgettransfer',
            name='approvel_3',
        ),
        migrations.RemoveField(
            model_name='xx_budgettransfer',
            name='approvel_3_date',
        ),
        migrations.RemoveField(
            model_name='xx_budgettransfer',
            name='approvel_4',
        ),
        migrations.RemoveField(
            model_name='xx_budgettransfer',
            name='approvel_4_date',
        ),
        migrations.RemoveField(
            model_name='xx_budgettransfer',
            name='gl_posting_status',
        ),
        migrations.AddField(
            model_name='xx_budgettransfer',
            name='linked_transfer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
