# Generated by Django 4.2.7 on 2025-12-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_xx_securitygrouprole_default_abilities_and_more'),
        ('budget_management', '0006_remove_xx_budgettransfer_approvel_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_budgettransfer',
            name='security_group',
            field=models.ForeignKey(blank=True, help_text='Security group that has access to this transaction. If set, only members of this group can view/edit this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_transfers', to='user_management.xx_securitygroup'),
        ),
    ]
