# Generated by Django 5.2.1 on 2025-11-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Envelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('envelope', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
            options={
                'db_table': 'XX_PROJECT_ENVELOPE_XX',
            },
        ),
        migrations.CreateModel(
            name='XX_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('parent', models.CharField(blank=True, max_length=50, null=True)),
                ('alias_default', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'XX_ACCOUNT_XX',
            },
        ),
        migrations.CreateModel(
            name='XX_Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=50)),
                ('parent', models.CharField(blank=True, max_length=50, null=True)),
                ('alias_default', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'XX_ENTITY_XX',
            },
        ),
        migrations.CreateModel(
            name='XX_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('parent', models.CharField(blank=True, max_length=50, null=True)),
                ('alias_default', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'XX_PROJECT_XX',
            },
        ),
        migrations.CreateModel(
            name='XX_SegmentType',
            fields=[
                ('segment_id', models.IntegerField(help_text='Unique segment identifier', primary_key=True, serialize=False)),
                ('segment_name', models.CharField(help_text="Display name (e.g., 'Entity', 'Account', 'Project')", max_length=50, unique=True)),
                ('segment_type', models.CharField(help_text="Technical type (e.g., 'cost_center', 'account', 'project')", max_length=50)),
                ('oracle_segment_number', models.IntegerField(help_text='Maps to Oracle SEGMENT1, SEGMENT2, etc.')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this segment is required in transactions')),
                ('has_hierarchy', models.BooleanField(default=False, help_text='Whether this segment supports parent-child relationships')),
                ('max_length', models.IntegerField(default=50, help_text='Maximum code length for this segment')),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying in UI (lower = first)')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this segment represents', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this segment is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Segment Type',
                'verbose_name_plural': 'Segment Types',
                'db_table': 'XX_SEGMENT_TYPE_XX',
                'ordering': ['display_order', 'segment_id'],
            },
        ),
        migrations.CreateModel(
            name='XX_TransactionAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('transfer_id', models.IntegerField(blank=True, null=True)),
                ('transcation_code', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_center_code', models.CharField(blank=True, max_length=50, null=True)),
                ('account_code', models.CharField(blank=True, max_length=50, null=True)),
                ('project_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'XX_TRANSACTION_AUDIT_XX',
            },
        ),
        migrations.CreateModel(
            name='Account_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_account', models.CharField(max_length=50)),
                ('target_account', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'XX_ACCOUNT_MAPPING_LEGACY_XX',
                'unique_together': {('source_account', 'target_account')},
            },
        ),
        migrations.CreateModel(
            name='Budget_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('FY24_budget', models.DecimalField(decimal_places=2, max_digits=30)),
                ('FY25_budget', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
            options={
                'db_table': 'BUDGET_DATA_XX',
                'unique_together': {('project', 'account')},
            },
        ),
        migrations.CreateModel(
            name='XX_ACCOUNT_ENTITY_LIMIT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('project_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_transer_allowed_for_source', models.CharField(blank=True, max_length=255, null=True)),
                ('is_transer_allowed_for_target', models.CharField(blank=True, max_length=255, null=True)),
                ('is_transer_allowed', models.CharField(blank=True, max_length=255, null=True)),
                ('source_count', models.IntegerField(blank=True, null=True)),
                ('target_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'XX_ACCOUNT_ENTITY_LIMIT_XX',
                'unique_together': {('account_id', 'entity_id')},
            },
        ),
        migrations.CreateModel(
            name='XX_ACCOUNT_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_account', models.CharField(max_length=50)),
                ('target_account', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'XX_ACCOUNT_MAPPING__elies_XX',
                'unique_together': {('source_account', 'target_account')},
            },
        ),
        migrations.CreateModel(
            name='XX_BalanceReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('control_budget_name', models.CharField(blank=True, help_text='Control Budget Name', max_length=100, null=True)),
                ('ledger_name', models.CharField(blank=True, help_text='Ledger Name', max_length=100, null=True)),
                ('as_of_period', models.CharField(blank=True, help_text='As of Period (e.g., Sep-25)', max_length=20, null=True)),
                ('segment1', models.CharField(blank=True, help_text='Segment 1 (Cost Center)', max_length=50, null=True)),
                ('segment2', models.CharField(blank=True, help_text='Segment 2 (Account)', max_length=50, null=True)),
                ('segment3', models.CharField(blank=True, help_text='Segment 3 (Project)', max_length=50, null=True)),
                ('encumbrance_ytd', models.DecimalField(blank=True, decimal_places=2, help_text='Encumbrance Year to Date', max_digits=20, null=True)),
                ('other_ytd', models.DecimalField(blank=True, decimal_places=2, help_text='Other Year to Date', max_digits=20, null=True)),
                ('actual_ytd', models.DecimalField(blank=True, decimal_places=2, help_text='Actual Year to Date', max_digits=20, null=True)),
                ('funds_available_asof', models.DecimalField(blank=True, decimal_places=2, help_text='Funds Available As Of', max_digits=20, null=True)),
                ('budget_ytd', models.DecimalField(blank=True, decimal_places=2, help_text='Budget Year to Date', max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Balance Report',
                'verbose_name_plural': 'Balance Reports',
                'db_table': 'XX_BALANCE_REPORT_XX',
                'indexes': [models.Index(fields=['control_budget_name', 'as_of_period'], name='XX_BALANCE__control_ba7cc4_idx'), models.Index(fields=['segment1', 'segment2', 'segment3'], name='XX_BALANCE__segment_8c711d_idx'), models.Index(fields=['as_of_period'], name='XX_BALANCE__as_of_p_67c5e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='XX_DynamicBalanceReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('control_budget_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ledger_name', models.CharField(blank=True, max_length=100, null=True)),
                ('as_of_period', models.CharField(blank=True, max_length=20, null=True)),
                ('segment_values', models.JSONField(default=dict, help_text='JSON mapping of segment_type_id -> segment_code')),
                ('encumbrance_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('other_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('actual_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('funds_available_asof', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('budget_ytd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Balance Report',
                'verbose_name_plural': 'Dynamic Balance Reports',
                'db_table': 'XX_DYNAMIC_BALANCE_REPORT_XX',
                'indexes': [models.Index(fields=['control_budget_name', 'as_of_period'], name='XX_DYNAMIC__control_b61541_idx'), models.Index(fields=['as_of_period'], name='XX_DYNAMIC__as_of_p_36d2c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='XX_Entity_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_entity', models.CharField(max_length=50)),
                ('target_entity', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'XX_ENTITY_MAPPING__elies_XX',
                'unique_together': {('source_entity', 'target_entity')},
            },
        ),
        migrations.CreateModel(
            name='XX_PivotFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
                ('project', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField()),
                ('actual', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('fund', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('encumbrance', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
            ],
            options={
                'db_table': 'XX_PIVOTFUND_XX',
                'constraints': [models.UniqueConstraint(fields=('entity', 'account', 'project', 'year'), name='unique_entity_account_year')],
            },
        ),
        migrations.CreateModel(
            name='XX_SegmentEnvelope',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('segment_combination', models.JSONField(help_text='JSON mapping of segment_type_id -> segment_code representing the envelope scope')),
                ('envelope_amount', models.DecimalField(decimal_places=2, help_text='Total envelope/budget amount for this segment combination', max_digits=30)),
                ('fiscal_year', models.CharField(blank=True, help_text="Fiscal year for this envelope (e.g., 'FY2025')", max_length=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this envelope', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this envelope is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Segment Envelope',
                'verbose_name_plural': 'Segment Envelopes',
                'db_table': 'XX_SEGMENT_ENVELOPE_XX',
                'indexes': [models.Index(fields=['fiscal_year', 'is_active'], name='XX_SEGMENT__fiscal__4ed754_idx')],
            },
        ),
        migrations.CreateModel(
            name='XX_SegmentTransferLimit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('segment_combination', models.JSONField(help_text='JSON mapping of segment_type_id -> segment_code for this limit rule')),
                ('is_transfer_allowed_as_source', models.BooleanField(default=True, help_text='Can this segment combination be used as a transfer source?')),
                ('is_transfer_allowed_as_target', models.BooleanField(default=True, help_text='Can this segment combination be used as a transfer target?')),
                ('is_transfer_allowed', models.BooleanField(default=True, help_text='Are transfers allowed for this segment combination at all?')),
                ('source_count', models.IntegerField(blank=True, help_text='Number of times used as source (for tracking)', null=True)),
                ('target_count', models.IntegerField(blank=True, help_text='Number of times used as target (for tracking)', null=True)),
                ('max_source_transfers', models.IntegerField(blank=True, help_text='Maximum allowed transfers as source (null = unlimited)', null=True)),
                ('max_target_transfers', models.IntegerField(blank=True, help_text='Maximum allowed transfers as target (null = unlimited)', null=True)),
                ('fiscal_year', models.CharField(blank=True, help_text='Fiscal year this limit applies to', max_length=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this transfer limit', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this limit is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Segment Transfer Limit',
                'verbose_name_plural': 'Segment Transfer Limits',
                'db_table': 'XX_SEGMENT_TRANSFER_LIMIT_XX',
                'indexes': [models.Index(fields=['fiscal_year', 'is_active'], name='XX_SEGMENT__fiscal__a731d6_idx'), models.Index(fields=['is_active'], name='XX_SEGMENT__is_acti_9fa9bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='XX_Segment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='The actual segment code/value', max_length=50)),
                ('parent_code', models.CharField(blank=True, help_text='Parent segment code for hierarchical segments', max_length=50, null=True)),
                ('alias', models.CharField(blank=True, help_text='Display name / description', max_length=255, null=True)),
                ('level', models.IntegerField(default=0, help_text='Hierarchy level (0 = root)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this segment value is active')),
                ('envelope_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Envelope/budget limit for this segment (if applicable)', max_digits=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment_type', models.ForeignKey(help_text='Which segment type this value belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='account_and_entitys.xx_segmenttype')),
            ],
            options={
                'verbose_name': 'Segment Value',
                'verbose_name_plural': 'Segment Values',
                'db_table': 'XX_SEGMENT_XX',
            },
        ),
        migrations.CreateModel(
            name='XX_BalanceReportSegment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('segment_code', models.CharField(blank=True, help_text='Segment code (denormalized for performance, synced from segment_value)', max_length=50, null=True)),
                ('oracle_field_name', models.CharField(blank=True, help_text='Oracle field name (SEGMENT1, SEGMENT2, etc.)', max_length=20, null=True)),
                ('oracle_field_number', models.IntegerField(blank=True, help_text='Oracle segment position (1-30)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_report', models.ForeignKey(help_text='Parent balance report record', on_delete=django.db.models.deletion.CASCADE, related_name='balance_segments', to='account_and_entitys.xx_balancereport')),
                ('segment_value', models.ForeignKey(blank=True, help_text='Specific segment value (e.g., E001, A100, P001)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_report_usages', to='account_and_entitys.xx_segment')),
                ('segment_type', models.ForeignKey(help_text='Type of segment (Entity, Account, Project, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='balance_report_segments', to='account_and_entitys.xx_segmenttype')),
            ],
            options={
                'verbose_name': 'Balance Report Segment',
                'verbose_name_plural': 'Balance Report Segments',
                'db_table': 'XX_BALANCE_REPORT_SEGMENT_XX',
                'ordering': ['balance_report', 'oracle_field_number'],
            },
        ),
        migrations.CreateModel(
            name='XX_TransactionSegment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_segment_value', models.ForeignKey(blank=True, help_text='Source segment for transfers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='account_and_entitys.xx_segment')),
                ('segment_type', models.ForeignKey(help_text='Which segment type (Entity, Account, etc.)', on_delete=django.db.models.deletion.CASCADE, to='account_and_entitys.xx_segmenttype')),
                ('segment_value', models.ForeignKey(help_text='The specific segment value', on_delete=django.db.models.deletion.CASCADE, to='account_and_entitys.xx_segment')),
                ('to_segment_value', models.ForeignKey(blank=True, help_text='Destination segment for transfers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='account_and_entitys.xx_segment')),
                ('transaction_transfer', models.ForeignKey(help_text='The transaction this segment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_segments', to='transaction.xx_transactiontransfer')),
            ],
            options={
                'verbose_name': 'Transaction Segment',
                'verbose_name_plural': 'Transaction Segments',
                'db_table': 'XX_TRANSACTION_SEGMENT_XX',
            },
        ),
        migrations.CreateModel(
            name='XX_SegmentMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mapping_type', models.CharField(default='STANDARD', help_text='Type of mapping: STANDARD, ALIAS, CONSOLIDATION, etc.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of this mapping rule', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this mapping is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_segment', models.ForeignKey(help_text='The source segment value', on_delete=django.db.models.deletion.CASCADE, related_name='mappings_as_source', to='account_and_entitys.xx_segment')),
                ('target_segment', models.ForeignKey(help_text='The target segment value that source maps to', on_delete=django.db.models.deletion.CASCADE, related_name='mappings_as_target', to='account_and_entitys.xx_segment')),
                ('segment_type', models.ForeignKey(help_text='The segment type this mapping applies to', on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='account_and_entitys.xx_segmenttype')),
            ],
            options={
                'verbose_name': 'Segment Mapping',
                'verbose_name_plural': 'Segment Mappings',
                'db_table': 'XX_SEGMENT_MAPPING_XX',
                'indexes': [models.Index(fields=['segment_type', 'source_segment'], name='XX_SEGMENT__segment_6d786f_idx'), models.Index(fields=['segment_type', 'target_segment'], name='XX_SEGMENT__segment_8c367b_idx'), models.Index(fields=['is_active'], name='XX_SEGMENT__is_acti_4ad863_idx')],
                'unique_together': {('segment_type', 'source_segment', 'target_segment')},
            },
        ),
        migrations.AddIndex(
            model_name='xx_segment',
            index=models.Index(fields=['segment_type', 'code'], name='XX_SEGMENT__segment_74fd90_idx'),
        ),
        migrations.AddIndex(
            model_name='xx_segment',
            index=models.Index(fields=['segment_type', 'parent_code'], name='XX_SEGMENT__segment_05aa6d_idx'),
        ),
        migrations.AddIndex(
            model_name='xx_segment',
            index=models.Index(fields=['code'], name='XX_SEGMENT__code_fd0bec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xx_segment',
            unique_together={('segment_type', 'code')},
        ),
        migrations.AddIndex(
            model_name='xx_balancereportsegment',
            index=models.Index(fields=['balance_report', 'segment_type'], name='XX_BALANCE__balance_44cf0b_idx'),
        ),
        migrations.AddIndex(
            model_name='xx_balancereportsegment',
            index=models.Index(fields=['segment_type', 'segment_code'], name='XX_BALANCE__segment_4c3f71_idx'),
        ),
        migrations.AddIndex(
            model_name='xx_balancereportsegment',
            index=models.Index(fields=['oracle_field_number'], name='XX_BALANCE__oracle__078eff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xx_balancereportsegment',
            unique_together={('balance_report', 'segment_type')},
        ),
        migrations.AddIndex(
            model_name='xx_transactionsegment',
            index=models.Index(fields=['transaction_transfer', 'segment_type'], name='XX_TRANSACT_transac_879534_idx'),
        ),
        migrations.AddIndex(
            model_name='xx_transactionsegment',
            index=models.Index(fields=['segment_value'], name='XX_TRANSACT_segment_3e60ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xx_transactionsegment',
            unique_together={('transaction_transfer', 'segment_type')},
        ),
    ]
