# Generated by Django 5.2.1 on 2025-11-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xx_segment',
            name='envelope_amount',
        ),
    ]
