# Generated by Django 5.2.5 on 2025-11-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0002_remove_envelope_amount_from_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='XX_Segment_Funds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Segment1', models.CharField(blank=True, help_text='Segment 1', max_length=50, null=True)),
                ('Segment2', models.CharField(blank=True, help_text='Segment 2', max_length=50, null=True)),
                ('Segment3', models.CharField(blank=True, help_text='Segment 3', max_length=50, null=True)),
                ('Segment4', models.CharField(blank=True, help_text='Segment 4', max_length=50, null=True)),
                ('Segment5', models.CharField(blank=True, help_text='Segment 5', max_length=50, null=True)),
                ('Segment6', models.CharField(blank=True, help_text='Segment 6', max_length=50, null=True)),
                ('Segment7', models.CharField(blank=True, help_text='Segment 7', max_length=50, null=True)),
                ('Segment8', models.CharField(blank=True, help_text='Segment 8', max_length=50, null=True)),
                ('Segment9', models.CharField(blank=True, help_text='Segment 9', max_length=50, null=True)),
                ('Segment10', models.CharField(blank=True, help_text='Segment 10', max_length=50, null=True)),
                ('Segment11', models.CharField(blank=True, help_text='Segment 11', max_length=50, null=True)),
                ('Segment12', models.CharField(blank=True, help_text='Segment 12', max_length=50, null=True)),
                ('Segment13', models.CharField(blank=True, help_text='Segment 13', max_length=50, null=True)),
                ('Segment14', models.CharField(blank=True, help_text='Segment 14', max_length=50, null=True)),
                ('Segment15', models.CharField(blank=True, help_text='Segment 15', max_length=50, null=True)),
                ('Segment16', models.CharField(blank=True, help_text='Segment 16', max_length=50, null=True)),
                ('Segment17', models.CharField(blank=True, help_text='Segment 17', max_length=50, null=True)),
                ('Segment18', models.CharField(blank=True, help_text='Segment 18', max_length=50, null=True)),
                ('Segment19', models.CharField(blank=True, help_text='Segment 19', max_length=50, null=True)),
                ('Segment20', models.CharField(blank=True, help_text='Segment 20', max_length=50, null=True)),
                ('Segment21', models.CharField(blank=True, help_text='Segment 21', max_length=50, null=True)),
                ('Segment22', models.CharField(blank=True, help_text='Segment 22', max_length=50, null=True)),
                ('Segment23', models.CharField(blank=True, help_text='Segment 23', max_length=50, null=True)),
                ('Segment24', models.CharField(blank=True, help_text='Segment 24', max_length=50, null=True)),
                ('Segment25', models.CharField(blank=True, help_text='Segment 25', max_length=50, null=True)),
                ('Segment26', models.CharField(blank=True, help_text='Segment 26', max_length=50, null=True)),
                ('Segment27', models.CharField(blank=True, help_text='Segment 27', max_length=50, null=True)),
                ('Segment28', models.CharField(blank=True, help_text='Segment 28', max_length=50, null=True)),
                ('Segment29', models.CharField(blank=True, help_text='Segment 29', max_length=50, null=True)),
                ('Segment30', models.CharField(blank=True, help_text='Segment 30', max_length=50, null=True)),
                ('CONTROL_BUDGET_NAME', models.CharField(blank=True, help_text='CONTROL_BUDGET_NAME', max_length=100, null=True)),
                ('PERIOD_NAME', models.CharField(blank=True, help_text='PERIOD_NAME', max_length=100, null=True)),
                ('FUNDS_AVAILABLE_PTD', models.DecimalField(blank=True, decimal_places=2, help_text='FUNDS_AVAILABLE_PTD', max_digits=20, null=True)),
                ('COMMITMENT_PTD', models.DecimalField(blank=True, decimal_places=2, help_text='COMMITMENT_PTD', max_digits=20, null=True)),
                ('OBLIGATION_PTD', models.DecimalField(blank=True, decimal_places=2, help_text='OBLIGATION_PTD', max_digits=20, null=True)),
                ('OTHER_PTD', models.DecimalField(blank=True, decimal_places=2, help_text='OTHER_PTD', max_digits=20, null=True)),
                ('ACTUAL_PTD', models.DecimalField(blank=True, decimal_places=2, help_text='ACTUAL_PTD', max_digits=20, null=True)),
                ('BUDGET_PTD', models.DecimalField(blank=True, decimal_places=2, help_text='BUDGET_PTD', max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Segment Funds',
                'verbose_name_plural': 'Segment Funds',
                'db_table': 'XX_SEGMENT_FUNDS_XX',
                'indexes': [models.Index(fields=['Segment1', 'Segment2', 'Segment3'], name='XX_SEGMENT__Segment_49c660_idx')],
            },
        ),
    ]
