# Generated by Django 5.2.5 on 2025-11-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0003_xx_segment_funds'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_segment_funds',
            name='ENCUMBRANCE_PTD',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='encumbrance_ptd', max_digits=20, null=True),
        ),
    ]
