# Generated by Django 5.2.5 on 2025-11-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0004_xx_segment_funds_encumbrance_ptd'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_segment_funds',
            name='BUDGET_ADJUSTMENTS',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='BUDGET_ADJUSTMENTS', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='xx_segment_funds',
            name='INITIAL_BUDGET',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='INITIAL_BUDGET', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='xx_segment_funds',
            name='TOTAL_BUDGET',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TOTAL_BUDGET', max_digits=20, null=True),
        ),
    ]
