# Generated by Django 5.2.5 on 2025-11-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0005_xx_segment_funds_budget_adjustments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XX_gfs_Mamping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('To_Value', models.CharField(max_length=50)),
                ('From_value', models.CharField(max_length=50)),
                ('Target_value', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'XX_GFS_MAPPING__XX',
                'unique_together': {('To_Value', 'Target_value')},
            },
        ),
    ]
