# Generated by Django 5.2.5 on 2025-11-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0006_xx_gfs_mamping'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_gfs_mamping',
            name='Target_alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
