# Generated by Django 5.2.5 on 2025-11-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0007_xx_gfs_mamping_target_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_gfs_mamping',
            name='Same',
            field=models.BooleanField(default=False),
        ),
    ]
