# Generated by Django 5.2.5 on 2025-11-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0008_xx_gfs_mamping_same'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xx_gfs_mamping',
            name='Same',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
