# Generated by Django 5.2.1 on 2025-11-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('delegate', 'Delegate')], max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggers_stage_completion', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'APPROVAL_ACTION',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('level_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('delegated', 'Delegated')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'APPROVAL_ASSIGNMENT',
            },
        ),
        migrations.CreateModel(
            name='ApprovalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'APPROVAL_DELEGATION',
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('completed_stage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'APPROVAL_WORKFLOW_INSTANCE',
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowStageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'APPROVAL_WORKFLOW_STAGE_INSTANCE',
                'ordering': ['workflow_instance', 'stage_template__order_index'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowStageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(help_text='1-based ordering of stages')),
                ('name', models.CharField(max_length=120)),
                ('decision_policy', models.CharField(choices=[('ALL', 'All must approve'), ('ANY', 'Any one can approve'), ('QUORUM', 'Quorum of approvals')], default='ALL', max_length=10)),
                ('quorum_count', models.PositiveIntegerField(blank=True, null=True)),
                ('required_role', models.CharField(blank=True, help_text='Optional user.role filter', max_length=50, null=True)),
                ('dynamic_filter_json', models.TextField(blank=True, help_text='Reserved for future dynamic filtering (store JSON string)', null=True)),
                ('allow_reject', models.BooleanField(default=True)),
                ('allow_delegate', models.BooleanField(default=False)),
                ('sla_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('parallel_group', models.PositiveIntegerField(blank=True, help_text='Future use: stages in same group run in parallel', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'APPROVAL_WORKFLOW_STAGE_TEMPLATE',
                'ordering': ['workflow_template', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('transfer_type', models.CharField(choices=[('FAR', 'FAR'), ('AFR', 'AFR'), ('FAD', 'FAD'), ('GEN', 'Generic')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'APPROVAL_WORKFLOW_TEMPLATE',
                'ordering': ['transfer_type', '-version', 'code'],
            },
        ),
    ]
