# Generated by Django 5.2.1 on 2025-11-07 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('budget_management', '0001_initial'),
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for system actions (auto-cancel, auto-skip, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action', to='approvals.approvalassignment'),
        ),
        migrations.AddField(
            model_name='approvaldelegation',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvaldelegation',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalworkflowinstance',
            name='budget_transfer',
            field=models.OneToOneField(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instance', to='budget_management.xx_budgettransfer'),
        ),
        migrations.AddField(
            model_name='approvalworkflowstageinstance',
            name='workflow_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_instances', to='approvals.approvalworkflowinstance'),
        ),
        migrations.AddField(
            model_name='approvaldelegation',
            name='stage_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='approvals.approvalworkflowstageinstance'),
        ),
        migrations.AddField(
            model_name='approvalassignment',
            name='stage_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='approvals.approvalworkflowstageinstance'),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='stage_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalworkflowstageinstance'),
        ),
        migrations.AddField(
            model_name='approvalworkflowstagetemplate',
            name='required_user_level',
            field=models.ForeignKey(help_text='If set, assignments will include users with this level', on_delete=django.db.models.deletion.PROTECT, related_name='stage_templates', to='user_management.xx_userlevel'),
        ),
        migrations.AddField(
            model_name='approvalworkflowstageinstance',
            name='stage_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_instances', to='approvals.approvalworkflowstagetemplate'),
        ),
        migrations.AddField(
            model_name='approvalworkflowinstance',
            name='current_stage_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_instances', to='approvals.approvalworkflowstagetemplate'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowtemplate',
            index=models.Index(fields=['transfer_type', 'is_active'], name='APPROVAL_WO_transfe_b62471_idx'),
        ),
        migrations.AddField(
            model_name='approvalworkflowstagetemplate',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='approvals.approvalworkflowtemplate'),
        ),
        migrations.AddField(
            model_name='approvalworkflowinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='approvals.approvalworkflowtemplate'),
        ),
        migrations.AddIndex(
            model_name='approvaldelegation',
            index=models.Index(fields=['active'], name='APPROVAL_DE_active_930ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalassignment',
            index=models.Index(fields=['user'], name='APPROVAL_AS_user_id_73b3bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalassignment',
            unique_together={('stage_instance', 'user')},
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['stage_instance', 'action'], name='APPROVAL_AC_stage_i_1436fd_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowstageinstance',
            index=models.Index(fields=['workflow_instance', 'status'], name='APPROVAL_WO_workflo_2c4573_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflowstagetemplate',
            unique_together={('workflow_template', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='approvalworkflowinstance',
            index=models.Index(fields=['status', 'current_stage_template'], name='APPROVAL_WO_status_54fe57_idx'),
        ),
    ]
