# Generated by Django 5.2.5 on 2025-11-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalworkflowtemplate',
            name='transfer_type',
            field=models.CharField(choices=[('FAR', 'FAR'), ('AFR', 'AFR'), ('FAD', 'FAD'), ('DFR', 'DFR'), ('GEN', 'Generic')], max_length=10),
        ),
    ]
