# Generated by Django 4.2.7 on 2025-12-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_alter_approvalworkflowtemplate_transfer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalworkflowtemplate',
            name='transfer_type',
            field=models.CharField(choices=[('FAR', 'FAR'), ('AFR', 'AFR'), ('FAD', 'FAD'), ('DFR', 'DFR'), ('HFR', 'HFR'), ('GEN', 'Generic')], max_length=10),
        ),
    ]
