# Generated by Django 4.2.7 on 2025-12-11 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_xx_securitygrouprole_default_abilities_and_more'),
        ('approvals', '0004_alter_approvalworkflowtemplate_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflowstagetemplate',
            name='security_group',
            field=models.ForeignKey(blank=True, help_text='If set, only members of this security group can approve at this stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_stage_templates', to='user_management.xx_securitygroup'),
        ),
        migrations.AlterField(
            model_name='approvalworkflowstagetemplate',
            name='required_user_level',
            field=models.ForeignKey(blank=True, help_text='If set, assignments will include users with this level', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage_templates', to='user_management.xx_userlevel'),
        ),
    ]
