# Generated by Django 4.2.7 on 2025-12-11 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget_management', '0007_xx_budgettransfer_security_group'),
        ('user_management', '0003_xx_securitygrouprole_default_abilities_and_more'),
        ('approvals', '0005_approvalworkflowstagetemplate_security_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XX_WorkflowTemplateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_order', models.PositiveIntegerField(default=1, help_text='Order of execution (1 = first workflow, 2 = second, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'XX_WORKFLOW_TEMPLATE_ASSIGNMENT',
                'ordering': ['security_group', 'execution_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='approvalworkflowinstance',
            options={'ordering': ['budget_transfer', 'execution_order']},
        ),
        migrations.AddField(
            model_name='approvalworkflowinstance',
            name='execution_order',
            field=models.PositiveIntegerField(default=1, help_text='Order of execution for this workflow (1 = first, 2 = second, etc.)'),
        ),
        migrations.AlterField(
            model_name='approvalworkflowinstance',
            name='budget_transfer',
            field=models.ForeignKey(db_column='transaction_id', help_text='The transfer this workflow belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='budget_management.xx_budgettransfer'),
        ),
        migrations.AlterField(
            model_name='approvalworkflowstagetemplate',
            name='required_role',
            field=models.ForeignKey(blank=True, help_text='Required role within the security group (e.g., Finance Manager, Unit Head). Users must have this role assigned in their security group membership to approve at this stage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_templates', to='user_management.xx_securitygrouprole'),
        ),
        migrations.AlterField(
            model_name='approvalworkflowstagetemplate',
            name='security_group',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Security group is now determined by XX_WorkflowTemplateAssignment. This field is kept for backward compatibility but should not be used in new workflows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_stage_templates', to='user_management.xx_securitygroup'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflowinstance',
            index=models.Index(fields=['budget_transfer', 'execution_order', 'status'], name='APPROVAL_WO_transac_830e85_idx'),
        ),
        migrations.AddField(
            model_name='xx_workflowtemplateassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xx_workflowtemplateassignment',
            name='security_group',
            field=models.ForeignKey(help_text='Security group that will use these workflows', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_assignments', to='user_management.xx_securitygroup'),
        ),
        migrations.AddField(
            model_name='xx_workflowtemplateassignment',
            name='workflow_template',
            field=models.ForeignKey(help_text='Workflow template to execute', on_delete=django.db.models.deletion.CASCADE, related_name='security_group_assignments', to='approvals.approvalworkflowtemplate'),
        ),
        migrations.AddField(
            model_name='approvalworkflowinstance',
            name='workflow_assignment',
            field=models.ForeignKey(blank=True, help_text='The assignment that created this workflow instance (tracks execution order)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances', to='approvals.xx_workflowtemplateassignment'),
        ),
        migrations.AddIndex(
            model_name='xx_workflowtemplateassignment',
            index=models.Index(fields=['security_group', 'is_active', 'execution_order'], name='XX_WORKFLOW_securit_c41d06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xx_workflowtemplateassignment',
            unique_together={('security_group', 'workflow_template')},
        ),
    ]
