# Generated by Django 4.2.7 on 2025-12-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_phase6_workflow_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='xx_workflowtemplateassignment',
            name='transaction_code_filter',
            field=models.CharField(blank=True, help_text="Transaction code prefix filter (e.g., 'FAR', 'DFR'). Leave blank for all transactions.", max_length=10, null=True),
        ),
    ]
