# Generated by Django 5.2.1 on 2025-11-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xx_Invoice',
            fields=[
                ('Invoice_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Invoice_Number', models.CharField(max_length=100, unique=True)),
                ('Invoice_Data', models.JSONField()),
                ('base64_file', models.TextField(default='')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
            options={
                'db_table': 'XX_INVOICE_XX',
            },
        ),
    ]
